workflows:
  web-build:
    name: Web Build
    max_build_duration: 30
    
    environment:
      node: 18.x
      npm: 9.x
    scripts:
      - name: Install dependencies
        script: npm install
      
      - name: Build web app
        script: |
          echo "✅ Web app ready - Snoopy vs Zombies"
          mkdir -p build
          cp index.html build/
          cp -r *.js build/ 2>/dev/null || true
          cp -r *.css build/ 2>/dev/null || true
          cp -r *.png build/ 2>/dev/null || true
          cp -r *.jpg build/ 2>/dev/null || true
          cp manifest.json build/
    artifacts:
      - build/**/*
    publishing:
      email:
        recipients:
          - tu-email@example.com
        notify:
          success: true
          failure: true
          
  android-build:
    name: Android Build (Cordova)
    max_build_duration: 60
    
    environment:
      java: 11
      node: 18.x
      npm: 9.x
      
    scripts:
      - name: Install Cordova
        script: npm install -g cordova
        
      - name: Create Cordova project
        script: |
          cordova create snoopy-android com.game.snoopy SnoopyVsZombies
          cd snoopy-android
          cordova platform add android
          
      - name: Add web files to www folder
        script: |
          cd snoopy-android
          cp ../index.html www/
          cp ../*.js www/ 2>/dev/null || true
          cp ../*.css www/ 2>/dev/null || true
          cp ../*.png www/ 2>/dev/null || true
          cp ../*.jpg www/ 2>/dev/null || true
          cp ../manifest.json www/
          
      - name: Build APK
        script: |
          cd snoopy-android
          cordova build android --release
          
    artifacts:
      - snoopy-android/platforms/android/app/build/outputs/apk/release/**/*.apk
      
    publishing:
      email:
        recipients:
          - tu-email@example.com
        notify:
          success: true
          failure: true