workflows:
  react-web:
    name: React Web Build
    instance_type: mac_mini_m2
    max_build_duration: 30

    environment:
      node: 18.x
      npm: 9.x

    scripts:
      - name: Install dependencies
        script: |
          cd react-app
          npm install

      - name: Build React app
        script: |
          cd react-app
          npm run build

      - name: Run tests
        script: |
          cd react-app
          npm test -- --passWithNoTests

    artifacts:
      - react-app/build/**/*

    publishing:
      email:
        recipients:
          - tu-email@example.com
        notify:
          success: true
          failure: true

  react-native-ios:
    name: React Native iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: latest
      cocoapods: default
      node: 18.x

    scripts:
      - name: Install dependencies
        script: |
          cd react-app
          npm install
          cd ios
          pod install

      - name: Build for iOS
        script: |
          cd react-app/ios
          xcodebuild -workspace SnoopyGame.xcworkspace -scheme SnoopyGame -configuration Release

    artifacts:
      - react-app/ios/build/**/*.ipa

  react-native-android:
    name: React Native Android Build
    instance_type: linux_x2
    max_build_duration: 60

    environment:
      java: 11
      ndk: 21.4.7075529
      cmake: 3.10.2
      node: 18.x

    scripts:
      - name: Install dependencies
        script: |
          cd react-app
          npm install

      - name: Build for Android
        script: |
          cd react-app/android
          ./gradlew assembleRelease

    artifacts:
      - react-app/android/app/build/outputs/**/*.apk
