workflows:
  react-native-android:
    name: React Native Android Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.game.snoopy"
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/android
          
      - name: Build React app
        script: |
          npm run build
          echo "✅ Build de React completado"
          ls -la build/
          
      - name: Initialize Capacitor
        script: |
          npx cap init "Snoopy vs Zombies" "com.game.snoopy" --web-dir=build
          echo "✅ Capacitor inicializado"
          
      - name: Add Android platform
        script: |
          npx cap add android
          echo "✅ Plataforma Android agregada"
          ls -la android/
          
      - name: Sync Capacitor
        script: |
          npx cap sync android
          echo "✅ Sync completado"
          
      - name: Build APK
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug --stacktrace
          echo ""
          echo "✅ APK generado:"
          find app/build/outputs/apk -name "*.apk" -ls
          
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk