workflows:
  android-build:
    name: React Native Android Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      java: 21
      node: 22.12.0
      vars:
        PACKAGE_NAME: "com.game.snoopy"
    triggering:
      events:
        - push
    scripts:
      - name: Install Capacitor
        script: |
          npm install @capacitor/core @capacitor/cli @capacitor/android
          
      - name: Prepare files
        script: |
          mkdir -p www
          cp index.html www/
          cp *.js www/ 2>/dev/null || true
          cp *.css www/ 2>/dev/null || true
          cp *.png www/ 2>/dev/null || true
          cp *.jpg www/ 2>/dev/null || true
          cp manifest.json www/ 2>/dev/null || true
          echo "✅ Archivos copiados a www:"
          ls -la www/
          
      - name: Initialize Capacitor
        script: |
          npx cap init "Snoopy vs Zombies" "com.game.snoopy" --web-dir=www
          
      - name: Add Android
        script: |
          npx cap add android
          npx cap sync android
          
      - name: Build APK
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug --stacktrace
          echo ""
          echo "✅ APK generado:"
          find app/build/outputs/apk -name "*.apk" -ls
          
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk